name: 'setup-headless-display-action'
description: 'Set up a headless display using xvfb on Linux.'
author: PyVista Developers'
inputs:
  debug:
    description: 'Run debug commands'
    required: false
    default: false
branding:
  icon: 'monitor'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - name: Install GL Dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install libgl1-mesa-glx xvfb -y
    - name: Configure headless display
      shell: bash
      run: |
        export DISPLAY=:99.0
        echo "DISPLAY=:99.0" >> $GITHUB_ENV
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - name: Debug
      shell: bash
      if: ${{ inputs.debug == 'true' }}
      run: |
        ls -l /etc/init.d/
        sh -e /etc/init.d/xvfb start
    - name: Give xvfb some time to start
      shell: bash
      run: sleep 3
    - name: Configure for PyVista because we intend this to be used with PyVista
      shell: bash
      run: |
        export PYVISTA_OFF_SCREEN=True
        echo "PYVISTA_OFF_SCREEN=True" >> $GITHUB_ENV
