name: Local Testing

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Action
        uses: ./

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install PyVista
        run: pip install pyvista

      - name: Test PyVista
        run: python test_pyvista.py

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-sphere
          path: sphere.png

      - name: Second test of PyVista
        run: python -c "import pyvista;pyvista.Cube().plot(screenshot='${{ matrix.os }}-cube.png')"

      - uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.os }}-cube.png
